name: Deploy Docker image
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'CODEOWNERS'
    branches:
      - master
jobs:
  deploy-docker-image:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Sette opp Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installere dependencies
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
      - name: Tester og linting
        run: yarn test && yarn less:lint
      - name: Bygge dist
        run: yarn build
      - name: Sette Docker-navn og -tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/k9-sak-web
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Bygge Docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Laste opp Docker image
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push $(cat .docker_image):$(cat .docker_tag)
          docker tag $(cat .docker_image):$(cat .docker_tag) $(cat .docker_image):latest
          docker push $(cat .docker_image):latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


