name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/k9-sak-web

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Set variabler for image, namespace og cluster
        shell: bash
        run: |
          echo "TAG=$(echo ${{ github.event.client_payload.github.payload.issue.title }} | awk '{print $NF}' | awk -F- '{print $NF}')" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE_BASE:$(echo ${{ github.event.client_payload.github.payload.issue.title }} | awk '{print $NF}')" >> $GITHUB_ENV
          echo "CLUSTER=${{ github.event.client_payload.slash_command.arg1 }}" >> $GITHUB_ENV
          echo "NAMESPACE=${{ github.event.client_payload.slash_command.arg2 }}" >> $GITHUB_ENV

      - name: Sjekk ut kode
        uses: uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}

      - name: Promoter til cluster og namespace
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: deploy/${{ env.CLUSTER }}-${{ env.NAMESPACE }}.yml

      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: 'promote til ${{ github.event.client_payload.slash_command.args }} feilet'})

      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    body: 'promote til ${{ github.event.client_payload.slash_command.args }} utført'})
            github.issues.addLabels({...issue, labels: ['deployment','${{ env.CLUSTER }}-${{ env.NAMESPACE }}']})

      #  https://github.com/getsentry/action-release/issues/21
      #  TODO fikse riktig enviroment, i sentry så er det app-q1.adeo.no og app.adeo.no. ${{ env.CLUSTER }}
      #- name: Send versjonsnummer og source maps til Sentry
      #  if: success()
      #  uses: getsentry/action-release@v1.0.2
      #  env:
      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #    SENTRY_URL: ${{ secrets.SENTRY_URL }}
      #    SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      #  with:
      #    environment: 'app-q1.adeo.no'
      #    version: ${{ env.TAG }}
      #    sourcemaps: './dist'
